/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author SALA 14
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chbx_qualification_01 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txt_weighing_total = new javax.swing.JTextField();
        txt_weighing_01 = new javax.swing.JTextField();
        lbl_percentage_icon_01 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_qualification_01 = new javax.swing.JTextField();
        txt_qualification_02 = new javax.swing.JTextField();
        chbx_qualification_02 = new javax.swing.JCheckBox();
        txt_weighing_02 = new javax.swing.JTextField();
        lbl_percentage_icon_02 = new javax.swing.JLabel();
        txt_qualification_03 = new javax.swing.JTextField();
        chbx_qualification_03 = new javax.swing.JCheckBox();
        txt_weighing_03 = new javax.swing.JTextField();
        lbl_percentage_icon_03 = new javax.swing.JLabel();
        txt_qualification_04 = new javax.swing.JTextField();
        chbx_qualification_04 = new javax.swing.JCheckBox();
        txt_weighing_04 = new javax.swing.JTextField();
        lbl_percentage_icon_04 = new javax.swing.JLabel();
        txt_weighing_06 = new javax.swing.JTextField();
        lbl_percentage_icon_06 = new javax.swing.JLabel();
        txt_qualification_05 = new javax.swing.JTextField();
        chbx_qualification_05 = new javax.swing.JCheckBox();
        txt_weighing_05 = new javax.swing.JTextField();
        lbl_percentage_icon_05 = new javax.swing.JLabel();
        txt_qualification_06 = new javax.swing.JTextField();
        chbx_qualification_06 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        btn_calculate = new javax.swing.JButton();
        txt_qualification_final = new javax.swing.JTextField();
        lbl_qualification_final1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CalculApp");

        chbx_qualification_01.setText("Nota 1");

        jLabel1.setText("Ponderación");

        txt_weighing_total.setEditable(false);
        txt_weighing_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_weighing_total.setText("0");

        txt_weighing_01.setEditable(false);
        txt_weighing_01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_weighing_01.setText("0");

        lbl_percentage_icon_01.setText("%");

        jLabel3.setText("Nota");

        txt_qualification_01.setEditable(false);
        txt_qualification_01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qualification_01.setText("0");

        txt_qualification_02.setEditable(false);
        txt_qualification_02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qualification_02.setText("0");

        chbx_qualification_02.setText("Nota 2");

        txt_weighing_02.setEditable(false);
        txt_weighing_02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_weighing_02.setText("0");

        lbl_percentage_icon_02.setText("%");

        txt_qualification_03.setEditable(false);
        txt_qualification_03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qualification_03.setText("0");

        chbx_qualification_03.setText("Nota 3");

        txt_weighing_03.setEditable(false);
        txt_weighing_03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_weighing_03.setText("0");

        lbl_percentage_icon_03.setText("%");

        txt_qualification_04.setEditable(false);
        txt_qualification_04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qualification_04.setText("0");

        chbx_qualification_04.setText("Nota 4");

        txt_weighing_04.setEditable(false);
        txt_weighing_04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_weighing_04.setText("0");

        lbl_percentage_icon_04.setText("%");

        txt_weighing_06.setEditable(false);
        txt_weighing_06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_weighing_06.setText("0");

        lbl_percentage_icon_06.setText("%");

        txt_qualification_05.setEditable(false);
        txt_qualification_05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qualification_05.setText("0");

        chbx_qualification_05.setText("Nota 5");

        txt_weighing_05.setEditable(false);
        txt_weighing_05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_weighing_05.setText("0");

        lbl_percentage_icon_05.setText("%");

        txt_qualification_06.setEditable(false);
        txt_qualification_06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qualification_06.setText("0");

        chbx_qualification_06.setText("Nota 6");

        jLabel10.setText("%");

        btn_calculate.setText("Calcular");

        txt_qualification_final.setEditable(false);
        txt_qualification_final.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qualification_final.setText("0");

        lbl_qualification_final1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_qualification_final1.setText("Tu nota final de la asignatura es: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbx_qualification_02)
                        .addGap(22, 22, 22)
                        .addComponent(txt_weighing_02, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_percentage_icon_02)
                        .addGap(18, 18, 18)
                        .addComponent(txt_qualification_02, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbx_qualification_01)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_weighing_01, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_percentage_icon_01)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txt_qualification_01))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chbx_qualification_03)
                        .addGap(22, 22, 22)
                        .addComponent(txt_weighing_03, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_percentage_icon_03)
                        .addGap(18, 18, 18)
                        .addComponent(txt_qualification_03))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chbx_qualification_04)
                        .addGap(22, 22, 22)
                        .addComponent(txt_weighing_04, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_percentage_icon_04)
                        .addGap(18, 18, 18)
                        .addComponent(txt_qualification_04))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chbx_qualification_05)
                        .addGap(22, 22, 22)
                        .addComponent(txt_weighing_05, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_percentage_icon_05)
                        .addGap(18, 18, 18)
                        .addComponent(txt_qualification_05))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbx_qualification_06)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_weighing_total, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txt_weighing_06, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_percentage_icon_06)
                                .addGap(18, 18, 18)
                                .addComponent(txt_qualification_06))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_qualification_final1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_qualification_final)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_qualification_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbx_qualification_01)
                            .addComponent(txt_weighing_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_percentage_icon_01))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_qualification_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chbx_qualification_02)
                        .addComponent(txt_weighing_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_percentage_icon_02)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_qualification_03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chbx_qualification_03)
                        .addComponent(txt_weighing_03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_percentage_icon_03)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_qualification_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chbx_qualification_04)
                        .addComponent(txt_weighing_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_percentage_icon_04)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_qualification_05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chbx_qualification_05)
                        .addComponent(txt_weighing_05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_percentage_icon_05)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_qualification_06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chbx_qualification_06)
                        .addComponent(txt_weighing_06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_percentage_icon_06)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_weighing_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_calculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_qualification_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_qualification_final1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.JCheckBox chbx_qualification_01;
    private javax.swing.JCheckBox chbx_qualification_02;
    private javax.swing.JCheckBox chbx_qualification_03;
    private javax.swing.JCheckBox chbx_qualification_04;
    private javax.swing.JCheckBox chbx_qualification_05;
    private javax.swing.JCheckBox chbx_qualification_06;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_percentage_icon_01;
    private javax.swing.JLabel lbl_percentage_icon_02;
    private javax.swing.JLabel lbl_percentage_icon_03;
    private javax.swing.JLabel lbl_percentage_icon_04;
    private javax.swing.JLabel lbl_percentage_icon_05;
    private javax.swing.JLabel lbl_percentage_icon_06;
    private javax.swing.JLabel lbl_qualification_final1;
    private javax.swing.JTextField txt_qualification_01;
    private javax.swing.JTextField txt_qualification_02;
    private javax.swing.JTextField txt_qualification_03;
    private javax.swing.JTextField txt_qualification_04;
    private javax.swing.JTextField txt_qualification_05;
    private javax.swing.JTextField txt_qualification_06;
    private javax.swing.JTextField txt_qualification_final;
    private javax.swing.JTextField txt_weighing_01;
    private javax.swing.JTextField txt_weighing_02;
    private javax.swing.JTextField txt_weighing_03;
    private javax.swing.JTextField txt_weighing_04;
    private javax.swing.JTextField txt_weighing_05;
    private javax.swing.JTextField txt_weighing_06;
    private javax.swing.JTextField txt_weighing_total;
    // End of variables declaration//GEN-END:variables
}
